### ISSUE TITLE
Bugg Report

### ISSUE THREAD

**Issue by DroopilyDrake96** [OguzhanUmutlu/ComplexCrates#12]
Hey, when I open a crate I cannot open a second crate or chests. PLS FIX

**Comment by reyyan987** [comment]
You have yo set it in config.yml that when a player is opening one crate he cannot open another or any other player can open that crate you have yo wait you can set that to false

**Comment by loeffelkap** [comment]
Whenever I create a box, it is deleted automatically after I reload, or after a while. Does anyone know why ... please fix.

**Comment by OguzhanUmutlu** [comment]
> You have yo set it in config.yml that when a player is opening one crate he cannot open another or any other player can open that crate you have yo wait you can set that to false

Thank you for responding.

**Comment by OguzhanUmutlu** [comment]
> Whenever I create a box, it is deleted automatically after I reload, or after a while. Does anyone know why ... please fix.

I think you made something wrong. Please create new issue.

**Comment by loeffelkap** [comment]
What I also noticed in the meantime is that the boxes are deleted when you restart, I don't think that's so good now, I often restart. Can this be fixed or is it a bug?

**Comment by loeffelkap** [comment]
Pls Fix
