### ISSUE TITLE
Make it so we can give multiple crate keys.

### ISSUE THREAD

**Issue by FriendlySpiderz** [OguzhanUmutlu/ComplexCrates#6]
Make it so that we can give multiple crate keys because at the moment, I can only give one crate key to players.

also sorry but I couldn’t create a pull request since it wasn’t working for me.

**Comment by OguzhanUmutlu** [comment]
So what do you want? Like /crate givemulti <player> <keys> ? 
Or /crate give-all <player> ?

**Comment by Lentou** [comment]
or /crate give (crate) (player/*) (keys)

* - all players

**Comment by FriendlySpiderz** [comment]
Just something as simple as /crate give (player) (keys)

**Comment by FriendlySpiderz** [comment]
And for keyall it can be /crate give-all (keys)

**Comment by OguzhanUmutlu** [comment]
Hmm okay im adding it.

**Comment by OguzhanUmutlu** [comment]
https://github.com/OguzhanUmutlu/ComplexCrates/commit/96cf34473491bed0c06181ba03c181c4ccd53387
Added it.

**Comment by OguzhanUmutlu** [comment]
Also wait "," is not the best choice for using multiple things because they can create crate with ","

**Comment by OguzhanUmutlu** [comment]
https://github.com/OguzhanUmutlu/ComplexCrates/commit/66a50d4e3184be5123efbb4df68a4742a854ae3d
Fixed it.
Usages:
/crate givekey (player) (key1) (key2) ....
/crate givekey-all (key1) (key2) ....
